// =====================================================================
// modules/postgres.bicep
//
// Manages the existing Postgres Flexible Server (`psql-n8n-01-dev-26070`)
// per D3 (reuse). The server and `n8n` database are referenced as
// `existing`; the `AllowAllAzureServices` firewall rule is declared
// idempotently (D7 — keep, with a known-future-work flag).
//
// Admin password rotation is handled out-of-band (Phase 7 cutover):
// - the live PG admin password is preserved in KV by manual seed OR
// - the PG admin is reset to the value generated by secrets-bootstrap.
// This module performs no password mutation.
// =====================================================================

targetScope = 'resourceGroup'

@description('Name of the existing Postgres Flexible Server.')
param postgresServerName string

@description('Name of the n8n database (already exists).')
param databaseName string = 'n8n'

resource pg 'Microsoft.DBforPostgreSQL/flexibleServers@2024-08-01' existing = {
  name: postgresServerName
}

resource n8nDb 'Microsoft.DBforPostgreSQL/flexibleServers/databases@2024-08-01' existing = {
  parent: pg
  name: databaseName
}

// Firewall: allow all Azure services (D7). Tightening to private endpoint
// is logged in MIGRATION-PLAN.md §7 future work.
resource fwAllowAzure 'Microsoft.DBforPostgreSQL/flexibleServers/firewallRules@2024-08-01' = {
  parent: pg
  name: 'AllowAllAzureServices'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '0.0.0.0'
  }
}

@description('Resource ID of the Postgres Flexible Server.')
output serverId string = pg.id

@description('FQDN of the Postgres server (host for n8n DB_POSTGRESDB_HOST).')
output fqdn string = pg.properties.fullyQualifiedDomainName

@description('Administrator login (host for n8n DB_POSTGRESDB_USER).')
output adminLogin string = pg.properties.administratorLogin

@description('Database name.')
output databaseName string = n8nDb.name
